"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-19 21:14:58.743275
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('subjects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('ai_conversations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_conversations_user_id'), ['user_id'], unique=False)

    op.create_table('exams',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('subject_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('exam_round', sa.String(), nullable=True),
    sa.Column('exam_date', sa.DateTime(), nullable=True),
    sa.Column('total_marks', sa.Float(), nullable=True),
    sa.Column('file_reference', sa.String(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('uploaded', 'queued', 'extracting', 'analysing_questions', 'generating_skills', 'aggregating', 'completed', 'failed', name='examstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exams_user_id'), ['user_id'], unique=False)

    op.create_table('ai_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_messages_conversation_id'), ['conversation_id'], unique=False)

    op.create_table('exam_analyses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('exam_id', sa.String(), nullable=False),
    sa.Column('percentage_score', sa.Float(), nullable=True),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('overall_strengths', sa.Text(), nullable=True),
    sa.Column('overall_weaknesses', sa.Text(), nullable=True),
    sa.Column('analysis_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id')
    )
    op.create_table('exam_questions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('exam_id', sa.String(), nullable=False),
    sa.Column('created_order', sa.Float(), nullable=False),
    sa.Column('question_number', sa.String(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=True),
    sa.Column('max_marks', sa.Float(), nullable=False),
    sa.Column('student_score', sa.Float(), nullable=True),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('subtopic', sa.String(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.Column('correctness', sa.Enum('correct', 'partially_correct', 'incorrect', 'unanswered', name='correctness'), nullable=True),
    sa.Column('question_type', sa.String(), nullable=True),
    sa.Column('source_reference', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exam_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_questions_exam_id'), ['exam_id'], unique=False)

    op.create_table('performance_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('subject_id', sa.String(), nullable=False),
    sa.Column('exam_id', sa.String(), nullable=False),
    sa.Column('score_percentage', sa.Float(), nullable=False),
    sa.Column('exam_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('performance_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_performance_snapshots_exam_id'), ['exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_performance_snapshots_user_id'), ['user_id'], unique=False)

    op.create_table('revision_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('source_exam_id', sa.String(), nullable=False),
    sa.Column('source_question_id', sa.String(), nullable=True),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('next_review_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['source_question_id'], ['exam_questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('revision_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revision_items_source_exam_id'), ['source_exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_revision_items_user_id'), ['user_id'], unique=False)

    op.create_table('skill_evidence',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('skill_id', sa.String(), nullable=False),
    sa.Column('exam_id', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=True),
    sa.Column('evidence_type', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['exam_questions.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skill_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skill_evidence_exam_id'), ['exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_skill_evidence_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skill_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skill_evidence_user_id'))
        batch_op.drop_index(batch_op.f('ix_skill_evidence_exam_id'))

    op.drop_table('skill_evidence')
    with op.batch_alter_table('revision_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revision_items_user_id'))
        batch_op.drop_index(batch_op.f('ix_revision_items_source_exam_id'))

    op.drop_table('revision_items')
    with op.batch_alter_table('performance_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_performance_snapshots_user_id'))
        batch_op.drop_index(batch_op.f('ix_performance_snapshots_exam_id'))

    op.drop_table('performance_snapshots')
    with op.batch_alter_table('exam_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_questions_exam_id'))

    op.drop_table('exam_questions')
    op.drop_table('exam_analyses')
    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_messages_conversation_id'))

    op.drop_table('ai_messages')
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exams_user_id'))

    op.drop_table('exams')
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_conversations_user_id'))

    op.drop_table('ai_conversations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('subjects')
    op.drop_table('skills')
    # ### end Alembic commands ###
